export const Customers = (state) => state.customer;
export const Users = (state) => state.users;
export const Categories = (state) => state.category;
export const Suppliers = (state) => state.supplier;
export const Manufacturer = (state) => state.manufacturer;
export const ParentsSelector = (state) => state.parent;
export const Product = (state) => state.product;
export const Adjustment = (state) => state.adjustment;
export const Counter = (state) => state.count;
