export const InputData = [
    { type: "text", name: "fname", label: "First Name", to: "/", submenu: [], icon: "fa fa-tachometer" },
    { type: "text",name: "lname", label: "Last Name", to: "/customer", submenu: [], icon: "fa fa-user" },
    { type: "text",name: "email", label: "Email", to: "/", submenu: [], icon: "icon fa-list-alt" },
    { type: "text",name: "phone", label: "Phone", to: "/", submenu: [], icon: "fa fa-arrow-circle-down" },
    { type: "text",name: "address",label: "Address", to: "/", submenu: [], icon: "fa fa-bar-chart" },
    { type: "text",name: "city", label: "City", to: "/", submenu: [], icon: "fa fa-shopping-cart" },
    { type: "number",name: "state", label: "State/Province", to: "/", submenu: [], icon: "fa fa-handshake-o" },
    { type: "number",name: "zip", label: "Zip", to: "/", submenu: [], icon: "fa fa-dollar" },
    { type: "text",name: "country", label: "Country", to: "/", submenu: [], icon: "fa fa-handshake-o" },
    { type: "text",name: "company", label: "Company",to: "/", submenu: [], icon: "fa fa-id-card-o" },
    { type: "text",name: "comments", label: "Comments", to: "/", submenu: [], icon: "fa fa-power-off" },
    { type: "number",name: "store", label: "Store", to: "/", submenu: [], icon: "fa fa-power-off" },
    { type: "number",name: "credit", label: "Credit", to: "/", submenu: [], icon: "fa fa-power-off" },
  ];